2024-02-27 15:34:11,495 - LogController.py[line:87] - ERROR: Traceback (most recent call last):
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\controller\PicController.py", line 55, in run
    Main = img_main()
TypeError: 'module' object is not callable

2024-02-27 15:34:11,498 - LogController.py[line:87] - ERROR: Traceback (most recent call last):
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\controller\PicController.py", line 55, in run
    Main = img_main()
TypeError: 'module' object is not callable

2024-02-27 15:59:15,173 - LogController.py[line:87] - ERROR: Traceback (most recent call last):
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\..\qt0223\view\LoadPage.py", line 252, in changePage
    self.cur_page = globals()[msg]()
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\..\qt0223\view\HistoryPage.py", line 50, in __init__
    self.InitUI()
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\..\qt0223\view\HistoryPage.py", line 74, in InitUI
    self.setTableWidget()
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\..\qt0223\view\HistoryPage.py", line 495, in setTableWidget
    text = MyReport().gethtml()
TypeError: gethtml() missing 3 required positional arguments: 'item_type', 'reagent_info', and 'nature_aver_str'

2024-02-27 16:55:32,173 - LogController.py[line:87] - ERROR: Traceback (most recent call last):
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\view\LoadPage.py", line 252, in changePage
    self.cur_page = globals()[msg]()
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\view\HistoryPage.py", line 50, in __init__
    self.InitUI()
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\view\HistoryPage.py", line 74, in InitUI
    self.setTableWidget()
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\view\HistoryPage.py", line 495, in setTableWidget
    text = MyReport().gethtml()
TypeError: gethtml() missing 3 required positional arguments: 'item_type', 'reagent_info', and 'nature_aver_str'

2024-02-27 17:15:32,559 - LogController.py[line:87] - ERROR: Traceback (most recent call last):
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\..\qt0223\view\LoadPage.py", line 252, in changePage
    self.cur_page = globals()[msg]()
KeyError: 'dataPage'

2024-02-27 17:28:31,726 - LogController.py[line:87] - ERROR: Traceback (most recent call last):
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\..\qt0223\view\DataPage.py", line 206, in getData
    self.setTableWidget(self.data['item_type'], self.allergy_info, self.data['nature_aver_str'])
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\..\qt0223\view\DataPage.py", line 293, in setTableWidget
    text = MyReport().gethtml(item_type, reagent_info, nature_aver_str)
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\..\qt0223\util\report.py", line 118, in gethtml
    temp_str = temp_str + str_temp % (str(j + 1) + reagent_info_list_3[j], result_list_3[j], result_list_4[j])
IndexError: list index out of range

2024-02-27 17:28:31,729 - LogController.py[line:87] - ERROR: Traceback (most recent call last):
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\..\qt0223\view\DataPage.py", line 206, in getData
    self.setTableWidget(self.data['item_type'], self.allergy_info, self.data['nature_aver_str'])
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\..\qt0223\view\DataPage.py", line 293, in setTableWidget
    text = MyReport().gethtml(item_type, reagent_info, nature_aver_str)
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\..\qt0223\util\report.py", line 118, in gethtml
    temp_str = temp_str + str_temp % (str(j + 1) + reagent_info_list_3[j], result_list_3[j], result_list_4[j])
IndexError: list index out of range

2024-02-27 17:29:02,914 - LogController.py[line:87] - ERROR: Traceback (most recent call last):
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\..\qt0223\view\DataPage.py", line 206, in getData
    self.setTableWidget(self.data['item_type'], self.allergy_info, self.data['nature_aver_str'])
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\..\qt0223\view\DataPage.py", line 293, in setTableWidget
    text = MyReport().gethtml(item_type, reagent_info, nature_aver_str)
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\..\qt0223\util\report.py", line 118, in gethtml
    temp_str = temp_str + str_temp % (str(j + 1) + reagent_info_list_3[j], result_list_3[j], result_list_4[j])
IndexError: list index out of range

2024-02-27 17:29:02,917 - LogController.py[line:87] - ERROR: Traceback (most recent call last):
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\..\qt0223\view\DataPage.py", line 206, in getData
    self.setTableWidget(self.data['item_type'], self.allergy_info, self.data['nature_aver_str'])
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\..\qt0223\view\DataPage.py", line 293, in setTableWidget
    text = MyReport().gethtml(item_type, reagent_info, nature_aver_str)
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\..\qt0223\util\report.py", line 118, in gethtml
    temp_str = temp_str + str_temp % (str(j + 1) + reagent_info_list_3[j], result_list_3[j], result_list_4[j])
IndexError: list index out of range

2024-02-27 17:33:08,280 - LogController.py[line:87] - ERROR: Traceback (most recent call last):
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\..\qt0223\view\DataPage.py", line 206, in getData
    self.setTableWidget(self.data['item_type'], self.allergy_info, self.data['nature_aver_str'])
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\..\qt0223\view\DataPage.py", line 293, in setTableWidget
    text = MyReport().gethtml(item_type, reagent_info, nature_aver_str)
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\..\qt0223\util\report.py", line 118, in gethtml
    temp_str = temp_str + str_temp % (str(j + 1) + reagent_info_list_3[j], result_list_3[j], result_list_4[j])
IndexError: list index out of range

2024-02-27 17:33:08,283 - LogController.py[line:87] - ERROR: Traceback (most recent call last):
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\..\qt0223\view\DataPage.py", line 206, in getData
    self.setTableWidget(self.data['item_type'], self.allergy_info, self.data['nature_aver_str'])
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\..\qt0223\view\DataPage.py", line 293, in setTableWidget
    text = MyReport().gethtml(item_type, reagent_info, nature_aver_str)
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\..\qt0223\util\report.py", line 118, in gethtml
    temp_str = temp_str + str_temp % (str(j + 1) + reagent_info_list_3[j], result_list_3[j], result_list_4[j])
IndexError: list index out of range

2024-02-27 17:33:55,020 - LogController.py[line:87] - ERROR: Traceback (most recent call last):
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\..\qt0223\view\DataPage.py", line 206, in getData
    self.setTableWidget(self.data['item_type'], self.allergy_info, self.data['nature_aver_str'])
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\..\qt0223\view\DataPage.py", line 293, in setTableWidget
    text = MyReport().gethtml(item_type, reagent_info, nature_aver_str)
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\..\qt0223\util\report.py", line 118, in gethtml
    temp_str = temp_str + str_temp % (str(j + 1) + reagent_info_list_3[j], result_list_3[j], result_list_4[j])
IndexError: list index out of range

2024-02-27 17:33:55,024 - LogController.py[line:87] - ERROR: Traceback (most recent call last):
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\..\qt0223\view\DataPage.py", line 206, in getData
    self.setTableWidget(self.data['item_type'], self.allergy_info, self.data['nature_aver_str'])
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\..\qt0223\view\DataPage.py", line 293, in setTableWidget
    text = MyReport().gethtml(item_type, reagent_info, nature_aver_str)
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\..\qt0223\util\report.py", line 118, in gethtml
    temp_str = temp_str + str_temp % (str(j + 1) + reagent_info_list_3[j], result_list_3[j], result_list_4[j])
IndexError: list index out of range

2024-02-28 10:49:38,520 - LogController.py[line:87] - ERROR: Traceback (most recent call last):
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\view\LoadPage.py", line 303, in showCurrentTime
    def showCurrentTime(self) -> None:
KeyboardInterrupt

2024-02-28 10:49:38,520 - LogController.py[line:87] - ERROR: Traceback (most recent call last):
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\view\LoadPage.py", line 303, in showCurrentTime
    def showCurrentTime(self) -> None:
KeyboardInterrupt

2024-02-28 11:09:32,264 - LogController.py[line:87] - ERROR: Traceback (most recent call last):
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\..\qt0223\view\LoadPage.py", line 264, in changePage
    self.cur_page = globals()[msg]()
KeyError: 'PerPage'

2024-02-28 11:10:35,479 - LogController.py[line:87] - ERROR: Traceback (most recent call last):
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\..\qt0223\view\LoadPage.py", line 264, in changePage
    self.cur_page = globals()[msg]()
KeyError: 'PerPage'

2024-02-28 11:10:52,094 - LogController.py[line:87] - ERROR: Traceback (most recent call last):
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\..\qt0223\view\LoadPage.py", line 264, in changePage
    self.cur_page = globals()[msg]()
KeyError: 'PerPage'

2024-02-28 11:18:15,573 - LogController.py[line:87] - ERROR: Traceback (most recent call last):
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\..\qt0223\view\LoadPage.py", line 264, in changePage
    self.cur_page = globals()[msg]()
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\..\qt0223\view\SysPage.py", line 31, in __init__
    self.InitUI()
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\..\qt0223\view\SysPage.py", line 40, in InitUI
    self.setBtnIcon()
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\..\qt0223\view\SysPage.py", line 72, in setBtnIcon
    self.ui.per_icon_label.setPixmap(pixImg)
AttributeError: 'Ui_Form' object has no attribute 'per_icon_label'

2024-02-28 11:18:50,632 - LogController.py[line:87] - ERROR: Traceback (most recent call last):
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\..\qt0223\view\LoadPage.py", line 264, in changePage
    self.cur_page = globals()[msg]()
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\..\qt0223\view\SysPage.py", line 31, in __init__
    self.InitUI()
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\..\qt0223\view\SysPage.py", line 40, in InitUI
    self.setBtnIcon()
  File "C:\Users\YGS_Tu\Desktop\code\python\qt0223\..\qt0223\view\SysPage.py", line 72, in setBtnIcon
    """
AttributeError: 'Ui_Form' object has no attribute 'per_icon_label'

